Repository gudtldn/W04-Engine, pull requests merged in 2025-04, with the labels that each got.

#14 Feat/cdo
  Week04/Engine/Source/Runtime/CoreUObject/UObject/NameTypes.cpp
  Week04/Engine/Source/Runtime/CoreUObject/UObject/NameTypes.h
  Week04/Engine/Source/Runtime/CoreUObject/UObject/Object.cpp
  Week04/Engine/Source/Runtime/CoreUObject/UObject/Object.h
  Week04/Engine/Source/Runtime/CoreUObject/UObject/ObjectFactory.h
  Week04/Engine/Source/Runtime/CoreUObject/UObject/ObjectMacros.h
  Week04/Engine/Source/Runtime/CoreUObject/UObject/UClass.cpp
  Week04/Engine/Source/Runtime/CoreUObject/UObject/UClass.h
  Week04/Engine/Source/Runtime/Engine/Classes/Actors/Player.cpp
  Week04/Engine/Source/Runtime/Engine/Classes/Components/ActorComponent.cpp
  Week04/Engine/Source/Runtime/Engine/Classes/Components/ActorComponent.h
  Week04/Engine/Source/Runtime/Engine/Classes/Components/SceneComponent.cpp
  Week04/Engine/Source/Runtime/Engine/Classes/Components/SceneComponent.h
  Week04/Engine/Source/Runtime/Engine/Classes/Components/UText.cpp
  Week04/Engine/Source/Runtime/Engine/World.cpp
  Week04/Engine/Source/Runtime/Engine/World.h
  Week04/Engine/Source/Runtime/InteractiveToolsFramework/BaseGizmos/TransformGizmo.cpp
  Week04/Engine/Source/Runtime/InteractiveToolsFramework/BaseGizmos/TransformGizmo.h
  Week04/Engine/Source/Runtime/Launch/EngineLoop.cpp
  Week04/Engine/Source/Runtime/Renderer/Renderer.cpp
Labels: size/L

#15 Hotfix/render
  Week04/Engine/Source/Editor/PropertyEditor/OutlinerEditorPanel.cpp
  Week04/Engine/Source/Editor/PropertyEditor/PropertyEditorPanel.cpp
  Week04/Engine/Source/Editor/UnrealEd/SceneMgr.cpp
  Week04/Engine/Source/Runtime/Core/EngineStatics.cpp
  Week04/Engine/Source/Runtime/CoreUObject/UObject/Object.h
  Week04/Engine/Source/Runtime/CoreUObject/UObject/ObjectFactory.h
  Week04/Engine/Source/Runtime/Engine/Classes/Actors/Player.cpp
  Week04/Engine/Source/Runtime/Engine/Classes/Engine/ResourceMgr.cpp
  Week04/Engine/Source/Runtime/Engine/World.h
  Week04/Engine/Source/Runtime/Launch/EngineLoop.cpp
Labels: size/M

#16 imgui button 클릭안되는 문제 해결
  Week04/Engine/Source/Editor/PropertyEditor/PlayEditorPanel.cpp
  Week04/Engine/Source/Editor/PropertyEditor/PlayEditorPanel.h
  Week04/Engine/Source/Editor/UnrealEd/UnrealEd.cpp
Labels: size/S
